### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Neluji/omz-todotxt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Neluji** [comment]
Thank you for letting me know of this oversight, I'll fix it right away 😉

(And also thanks for this clean and efficient resource !)
